version: 3
services:
  # Servizio per il backend Django
  backend:
    type: python
    runtime: python3.11
    build:
      dockerfile: ./backend/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DATABASE_URL: sqlite:///app/db.sqlite3  # Cambiato per usare SQLite
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  # Servizio per il frontend React
  frontend:
    type: nodejs
    runtime: node:18
    build:
      dockerfile: ./frontend/Dockerfile
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - backend

  # Servizio per il database SQLite
  db:
    image: nouchka/sqlite3
    environment:
      SQLITE_DATABASE_PATH: /app/db.sqlite3
    volumes:
      - ./backend/db.sqlite3:/app/db.sqlite3
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
